### ISSUE TITLE
Question: Are ConvNeXt models included in the paper graphs?

### ISSUE THREAD

**Issue by tlpss** [ngruver/lie-deriv#1]
from https://github.com/ngruver/lie-deriv/blob/9e265439714ab9a7a7ff8b067e3262858c92f2db/sweep_configs/e2e_configs.py#L179
it seems that ConvNext is included in the list of models, however I seem to be unable to find it in list of models in the paper:

![image](https://user-images.githubusercontent.com/37955681/195918783-6b970b5c-1781-4a37-aa1c-d45b01749247.png)
Are ConvNeXt models included in the figures? 

And would it by any chance be possible to release the result files? I would be interested in knowing the equivariance errors of certain model families.

**Comment by ngruver** [comment]
Hi Thomas!

Sorry for the confusion. The convnext results should be included in the figures. 

Here is a side-by-side plot of ConvNeXts and some ViTs, which we had in an earlier manuscript:
[convnext_vs_vit.pdf](https://github.com/ngruver/lie-deriv/files/9789578/convnext_vs_vit.pdf)

And here are all the end-to-end LEE results.
[all_results.csv](https://github.com/ngruver/lie-deriv/files/9789730/all_results.csv)

Note that the numbers (equivariance error and test accuracy) are calculated on a subset of the ImageNet test set, not the full official test set. 

Let me know if you have any other questions!

**Comment by tlpss** [comment]
Hi, thanks for the clarification and the additional results. Much appreciated!
